### ISSUE TITLE
Scripts do not work for pytorch version 0.4 and later

### ISSUE THREAD

**Issue by yuchi1989** [my89/imSitu#3]
Hi, the scripts do not work in pytorch version 0.4 and later. Please fix it if possible.

**Comment by my89** [comment]
Hi, I updated it to run in python 3.6 and pytorch 1.0 . Let me know if you have problems. The seem to no longer load either, other than the resnet 101 model, which gives slightly different results. I'll try to find some time to retrain the models for these new versions of pytorch a bit later. Thanks!

**Comment by njuaplusplus** [comment]
Hi Mark,

I am using python3 and newer PyTorch 1.5.

I wonder if you could provide:
1. some instructions to train the model (what commands, what hardware requirements)
2. the pre-trained weights.

I failed to evaluate the resnet101 using the command because of CUDA OOM :
```
python eval.py --format model --include baseline_crf.py --weights_file baseline_models/baseline_resnet_101 --encoding_file baseline_models/baseline_encoder --trust_encoder --batch_size 128 --image_dir resized_256/
```

And I couldn't load resent34 either because of some mismatched parameters.

Thank you very much.
